<?php
/**
 * Crawl Issues — issues table CRUD, run diffing, progress snapshot, and pruning.
 *
 * Provides static factory + query methods consumed by SWPS_Site_Crawler during
 * chunk processing and by SWPS_Site_Crawl_Audit during read-only rendering.
 *
 * No WordPress hook registrations live here — see SWPS_Site_Crawler for those.
 *
 * @package StrataWP_SEO
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Issues table access for site crawl runs.
 */
class SWPS_Crawl_Issues {

	/** Custom-table name (without prefix). */
	public const TABLE_ISSUES = 'swps_crawl_issues';
	public const TABLE_QUEUE  = 'swps_crawl_queue';
	public const TABLE_PAGES  = 'swps_crawl_pages';

	/** Current schema version; bump whenever the DDL changes. */
	public const DB_VERSION = '4';

	/** Option key holding the installed schema version. */
	public const OPT_DB_VER = 'swps_crawl_db_version';

	/** Number of completed runs to retain before pruning. */
	private const RUNS_TO_KEEP = 5;

	// =========================================================================
	// DB SCHEMA
	// =========================================================================

	/**
	 * Create/upgrade the crawl tables when the stored schema version is stale.
	 *
	 * Runs at init so existing installs get the tables on plugin update
	 * without a deactivate/reactivate cycle (SWPS_Bot_Analytics_Tracker
	 * precedent).
	 */
	public static function maybe_upgrade(): void {
		$installed = get_option( self::OPT_DB_VER );
		if ( self::DB_VERSION === $installed ) {
			return;
		}

		// v3 adds a UNIQUE KEY on (run_id, url_hash) to the pages table so
		// insert_page() can REPLACE instead of duplicating on re-processing.
		// Every pre-v3 row has url_hash '' (the column did not exist), which
		// collides across every row of a run once the unique index is added,
		// breaking dbDelta's ALTER TABLE. Page-facts rows are transient,
		// run-scoped audit data — regenerated by the next crawl and already
		// pruned after 5 runs, never referenced outside a run — so clearing
		// them ahead of the migration is safe, and simpler than backfilling
		// (which cannot resolve genuine pre-fix duplicate rows for the same
		// URL within a run anyway, since that duplication is exactly the bug
		// this version fixes).
		if ( $installed && version_compare( (string) $installed, '3', '<' ) ) {
			self::truncate_pre_v3_pages_table();
		}

		self::create_tables();
		update_option( self::OPT_DB_VER, self::DB_VERSION );
	}

	/**
	 * Clear the pages table ahead of the v3 migration, if it already exists.
	 *
	 * Guarded with a table-existence check so installs upgrading from before
	 * the pages table existed at all (DB_VERSION '1') don't error.
	 */
	private static function truncate_pre_v3_pages_table(): void {
		global $wpdb;
		$pages = $wpdb->prefix . self::TABLE_PAGES;
		// phpcs:disable WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.NoCaching,WordPress.DB.PreparedSQL.NotPrepared
		$exists = $wpdb->get_var( $wpdb->prepare( 'SHOW TABLES LIKE %s', $pages ) );
		if ( $exists === $pages ) {
			$wpdb->query( "TRUNCATE TABLE {$pages}" );
		}
		// phpcs:enable WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.NoCaching,WordPress.DB.PreparedSQL.NotPrepared
	}

	/**
	 * Create or upgrade crawl tables via dbDelta.
	 *
	 * Called on plugin activation and on DB-version mismatch at init.
	 * Safe to call multiple times (dbDelta is idempotent).
	 */
	public static function create_tables(): void {
		global $wpdb;

		$charset = $wpdb->get_charset_collate();
		$queue   = $wpdb->prefix . self::TABLE_QUEUE;
		$issues  = $wpdb->prefix . self::TABLE_ISSUES;
		$pages   = $wpdb->prefix . self::TABLE_PAGES;

		$sql_queue = "CREATE TABLE {$queue} (
			id         BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
			run_id     BIGINT UNSIGNED NOT NULL,
			url_hash   VARCHAR(64)     NOT NULL DEFAULT '',
			url        VARCHAR(2083)   NOT NULL DEFAULT '',
			depth      SMALLINT UNSIGNED NOT NULL DEFAULT 0,
			status     VARCHAR(10)     NOT NULL DEFAULT 'pending',
			found_on   VARCHAR(2083)   NOT NULL DEFAULT '',
			created_at DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
			PRIMARY KEY (id),
			UNIQUE KEY idx_run_hash (run_id, url_hash),
			KEY idx_run_status (run_id, status)
		) {$charset};";

		$sql_issues = "CREATE TABLE {$issues} (
			id             BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
			run_id         BIGINT UNSIGNED NOT NULL,
			type           VARCHAR(50)     NOT NULL DEFAULT '',
			url            VARCHAR(2083)   NOT NULL DEFAULT '',
			detail         LONGTEXT        NOT NULL DEFAULT '',
			severity       VARCHAR(10)     NOT NULL DEFAULT 'warning',
			post_id        BIGINT UNSIGNED             DEFAULT NULL,
			object_type    VARCHAR(10)                 DEFAULT NULL,
			object_id      BIGINT UNSIGNED             DEFAULT NULL,
			first_seen_run BIGINT UNSIGNED NOT NULL,
			PRIMARY KEY (id),
			KEY idx_run_id (run_id),
			KEY idx_type   (type)
		) {$charset};";

		$sql_pages = "CREATE TABLE {$pages} (
			id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
			run_id BIGINT UNSIGNED NOT NULL,
			url VARCHAR(500) NOT NULL,
			url_hash CHAR(32) NOT NULL DEFAULT '',
			status_code SMALLINT UNSIGNED NOT NULL DEFAULT 0,
			content_type VARCHAR(100) NOT NULL DEFAULT '',
			title TEXT,
			title_hash CHAR(32) NOT NULL DEFAULT '',
			meta_desc_hash CHAR(32) NOT NULL DEFAULT '',
			desc_length SMALLINT UNSIGNED NOT NULL DEFAULT 0,
			flags INT UNSIGNED NOT NULL DEFAULT 0,
			word_count INT UNSIGNED NOT NULL DEFAULT 0,
			html_bytes INT UNSIGNED NOT NULL DEFAULT 0,
			text_bytes INT UNSIGNED NOT NULL DEFAULT 0,
			h1_count SMALLINT UNSIGNED NOT NULL DEFAULT 0,
			canonical VARCHAR(500) DEFAULT NULL,
			internal_links LONGTEXT,
			unminified_assets TEXT,
			PRIMARY KEY  (id),
			UNIQUE KEY idx_run_urlhash (run_id, url_hash),
			KEY idx_run (run_id),
			KEY idx_run_title (run_id, title_hash),
			KEY idx_run_desc (run_id, meta_desc_hash)
		) {$charset};";

		require_once ABSPATH . 'wp-admin/includes/upgrade.php';
		dbDelta( $sql_queue );
		dbDelta( $sql_issues );
		dbDelta( $sql_pages );
	}

	// =========================================================================
	// WRITE HELPERS
	// =========================================================================

	/**
	 * Insert one issue row for the given run.
	 *
	 * Looks up (or creates) the first_seen_run value automatically.
	 *
	 * @param int        $run_id  Current run ID.
	 * @param string     $type    Issue type key (e.g. 'broken_link').
	 * @param string     $url     The URL that has the issue.
	 * @param array      $detail  Arbitrary details; JSON-encoded before storage.
	 * @param string     $severity 'error' | 'warning'.
	 * @param int|null   $post_id WordPress post ID when the URL maps to a post.
	 * @param array|null $target Polymorphic object target: array{object_type: string, object_id: int}.
	 */
	public static function insert_issue(
		int $run_id,
		string $type,
		string $url,
		array $detail,
		string $severity = 'warning',
		?int $post_id = null,
		?array $target = null
	): void {
		global $wpdb;

		$first_seen = self::get_first_seen_run( $type, $url, $run_id );
		$table      = $wpdb->prefix . self::TABLE_ISSUES;

		$object_type = null;
		$object_id   = null;
		if ( is_array( $target ) && ! empty( $target['object_type'] ) && 'none' !== $target['object_type'] ) {
			$object_type = (string) $target['object_type'];
			$object_id   = (int) ( $target['object_id'] ?? 0 );
			// Back-fill the legacy column so older readers keep working.
			if ( 'post' === $object_type && null === $post_id ) {
				$post_id = $object_id;
			}
		}

		// phpcs:disable WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.NoCaching
		$wpdb->insert(
			$table,
			array(
				'run_id'         => $run_id,
				'type'           => $type,
				'url'            => $url,
				'detail'         => wp_json_encode( $detail ),
				'severity'       => $severity,
				'post_id'        => $post_id,
				'object_type'    => $object_type,
				'object_id'      => $object_id,
				'first_seen_run' => $first_seen,
			),
			array(
				'%d',
				'%s',
				'%s',
				'%s',
				'%s',
				null === $post_id ? null : '%d',
				null === $object_type ? null : '%s',
				null === $object_id ? null : '%d',
				'%d',
			)
		);
		// phpcs:enable WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.NoCaching
	}

	/**
	 * Insert (or, on re-crawl of the same URL within a run, overwrite) one
	 * crawled-page facts row.
	 *
	 * Uses REPLACE against the (run_id, url_hash) unique key so re-processing
	 * a URL — e.g. after a crash between the previous insert_page() call and
	 * the queue row being marked 'done', which re-queues that one URL on the
	 * next chunk — overwrites the existing row instead of duplicating it.
	 *
	 * @param int   $run_id Current run ID.
	 * @param array $row    Page row with keys: url, status_code, content_type, title, title_hash,
	 *                       meta_desc_hash, desc_length, flags, word_count, html_bytes, text_bytes,
	 *                       h1_count, canonical, internal_links (array→JSON), unminified_assets (array→JSON).
	 */
	public static function insert_page( int $run_id, array $row ): void {
		global $wpdb;
		$url = substr( (string) ( $row['url'] ?? '' ), 0, 500 );
		$wpdb->replace( // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery
			$wpdb->prefix . self::TABLE_PAGES,
			array(
				'run_id'            => $run_id,
				'url'               => $url,
				'url_hash'          => md5( $url ),
				'status_code'       => (int) ( $row['status_code'] ?? 0 ),
				'content_type'      => substr( (string) ( $row['content_type'] ?? '' ), 0, 100 ),
				'title'             => (string) ( $row['title'] ?? '' ),
				'title_hash'        => (string) ( $row['title_hash'] ?? '' ),
				'meta_desc_hash'    => (string) ( $row['meta_desc_hash'] ?? '' ),
				'desc_length'       => (int) ( $row['desc_length'] ?? 0 ),
				'flags'             => (int) ( $row['flags'] ?? 0 ),
				'word_count'        => (int) ( $row['word_count'] ?? 0 ),
				'html_bytes'        => (int) ( $row['html_bytes'] ?? 0 ),
				'text_bytes'        => (int) ( $row['text_bytes'] ?? 0 ),
				'h1_count'          => (int) ( $row['h1_count'] ?? 0 ),
				'canonical'         => isset( $row['canonical'] ) ? substr( (string) $row['canonical'], 0, 500 ) : null,
				'internal_links'    => wp_json_encode( array_values( $row['internal_links'] ?? array() ) ),
				'unminified_assets' => wp_json_encode( array_values( $row['unminified_assets'] ?? array() ) ),
			)
		);
	}

	/**
	 * All page rows for a run, JSON columns decoded.
	 *
	 * @param int $run_id Target run ID.
	 * @return array[] Page rows with JSON columns decoded back to arrays.
	 */
	public static function pages_for_run( int $run_id ): array {
		global $wpdb;
		$table = $wpdb->prefix . self::TABLE_PAGES;
		$rows  = $wpdb->get_results( // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.PreparedSQL.InterpolatedNotPrepared
			$wpdb->prepare( "SELECT * FROM {$table} WHERE run_id = %d ORDER BY url ASC", $run_id ), // phpcs:ignore WordPress.DB.DirectDatabaseQuery.NoCaching
			ARRAY_A
		);
		foreach ( $rows as &$row ) {
			$row['internal_links']    = json_decode( (string) $row['internal_links'], true ) ?: array();
			$row['unminified_assets'] = json_decode( (string) $row['unminified_assets'], true ) ?: array();
			$row['flags']             = (int) $row['flags'];
			$row['status_code']       = (int) $row['status_code'];
		}
		return $rows;
	}

	/**
	 * Total / healthy (2xx, zero issues) / broken (>=400 or 0) page counts.
	 *
	 * @param int $run_id Target run ID.
	 * @return array{total:int, healthy:int, broken:int} Page counts.
	 */
	public static function page_counts( int $run_id ): array {
		global $wpdb;
		$pages       = $wpdb->prefix . self::TABLE_PAGES;
		$issues      = $wpdb->prefix . self::TABLE_ISSUES;
		$total       = (int) $wpdb->get_var( $wpdb->prepare( "SELECT COUNT(*) FROM {$pages} WHERE run_id = %d", $run_id ) ); // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.NoCaching,WordPress.DB.PreparedSQL.InterpolatedNotPrepared
		$broken      = (int) $wpdb->get_var( $wpdb->prepare( "SELECT COUNT(*) FROM {$pages} WHERE run_id = %d AND (status_code >= 400 OR status_code = 0)", $run_id ) ); // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.NoCaching,WordPress.DB.PreparedSQL.InterpolatedNotPrepared
		$with_issues = (int) $wpdb->get_var( $wpdb->prepare( "SELECT COUNT(DISTINCT p.url) FROM {$pages} p INNER JOIN {$issues} i ON i.run_id = p.run_id AND i.url = p.url WHERE p.run_id = %d", $run_id ) ); // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.NoCaching,WordPress.DB.PreparedSQL.InterpolatedNotPrepared
		return array(
			'total'   => $total,
			'healthy' => max( 0, $total - $with_issues ),
			'broken'  => $broken,
		);
	}

	// =========================================================================
	// READ HELPERS
	// =========================================================================

	/**
	 * Get the first run in which an issue of this type + URL was seen.
	 *
	 * Returns $current_run_id when no prior run contains the issue (new this run).
	 *
	 * @param string $type    Issue type string.
	 * @param string $url     Issue URL.
	 * @param int    $run_id  Current run ID.
	 * @return int First-seen run ID.
	 */
	public static function get_first_seen_run( string $type, string $url, int $run_id ): int {
		global $wpdb;

		$table = $wpdb->prefix . self::TABLE_ISSUES;

		// phpcs:disable WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.NoCaching,WordPress.DB.PreparedSQL.InterpolatedNotPrepared
		$prior = $wpdb->get_var(
			$wpdb->prepare(
				"SELECT MIN(first_seen_run) FROM {$table} WHERE type = %s AND url = %s AND run_id < %d",
				$type,
				$url,
				$run_id
			)
		);
		// phpcs:enable WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.NoCaching,WordPress.DB.PreparedSQL.InterpolatedNotPrepared

		return null !== $prior ? (int) $prior : $run_id;
	}

	/**
	 * Return a progress snapshot for the given run.
	 *
	 * @param int $run_id Target run ID.
	 * @return array{done:bool,crawled:int,queued:int,issues:int}
	 */
	public static function progress_snapshot( int $run_id ): array {
		global $wpdb;

		$queue_table  = $wpdb->prefix . self::TABLE_QUEUE;
		$issues_table = $wpdb->prefix . self::TABLE_ISSUES;

		// phpcs:disable WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.NoCaching,WordPress.DB.PreparedSQL.InterpolatedNotPrepared
		$crawled = (int) $wpdb->get_var(
			$wpdb->prepare(
				"SELECT COUNT(*) FROM {$queue_table} WHERE run_id = %d AND status = 'done'",
				$run_id
			)
		);
		$queued  = (int) $wpdb->get_var(
			$wpdb->prepare(
				"SELECT COUNT(*) FROM {$queue_table} WHERE run_id = %d AND status = 'pending'",
				$run_id
			)
		);
		$issues  = (int) $wpdb->get_var(
			$wpdb->prepare(
				"SELECT COUNT(*) FROM {$issues_table} WHERE run_id = %d",
				$run_id
			)
		);
		// phpcs:enable WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.NoCaching,WordPress.DB.PreparedSQL.InterpolatedNotPrepared

		return array(
			'done'    => ( 0 === $queued ),
			'crawled' => $crawled,
			'queued'  => $queued,
			'issues'  => $issues,
		);
	}

	/**
	 * Return issue counts grouped by type for the given run.
	 *
	 * @param int $run_id Target run ID.
	 * @return array[] Rows of {type, cnt}.
	 */
	public static function issue_counts( int $run_id ): array {
		global $wpdb;

		$table = $wpdb->prefix . self::TABLE_ISSUES;

		// phpcs:disable WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.NoCaching,WordPress.DB.PreparedSQL.InterpolatedNotPrepared
		$rows = (array) $wpdb->get_results(
			$wpdb->prepare(
				"SELECT type, COUNT(*) AS cnt FROM {$table} WHERE run_id = %d GROUP BY type",
				$run_id
			),
			ARRAY_A
		);
		// phpcs:enable WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.NoCaching,WordPress.DB.PreparedSQL.InterpolatedNotPrepared

		return $rows;
	}

	/**
	 * Return issue counts grouped by severity for the given run.
	 *
	 * @param int $run_id Target run ID.
	 * @return array{error:int,warning:int,notice:int}
	 */
	public static function severity_counts( int $run_id ): array {
		global $wpdb;

		$table = $wpdb->prefix . self::TABLE_ISSUES;

		// phpcs:disable WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.NoCaching,WordPress.DB.PreparedSQL.InterpolatedNotPrepared
		$rows = (array) $wpdb->get_results(
			$wpdb->prepare(
				"SELECT severity, COUNT(*) AS cnt FROM {$table} WHERE run_id = %d GROUP BY severity",
				$run_id
			),
			ARRAY_A
		);
		// phpcs:enable WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.NoCaching,WordPress.DB.PreparedSQL.InterpolatedNotPrepared

		$counts = array(
			'error'   => 0,
			'warning' => 0,
			'notice'  => 0,
		);
		foreach ( $rows as $row ) {
			$severity = (string) ( $row['severity'] ?? '' );
			if ( isset( $counts[ $severity ] ) ) {
				$counts[ $severity ] = (int) $row['cnt'];
			}
		}

		return $counts;
	}

	/**
	 * Return all issue rows for a run, detail JSON decoded, grouped by type.
	 *
	 * Each row gains an 'is_new' flag: true when first_seen_run equals the
	 * queried run (i.e. the issue was not present in any earlier run).
	 *
	 * @param int $run_id Target run ID.
	 * @return array<string, array[]> Issue rows keyed by type.
	 */
	public static function issues_for_run( int $run_id ): array {
		global $wpdb;

		$table = $wpdb->prefix . self::TABLE_ISSUES;

		// phpcs:disable WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.NoCaching,WordPress.DB.PreparedSQL.InterpolatedNotPrepared
		$rows = (array) $wpdb->get_results(
			$wpdb->prepare(
				"SELECT id, type, url, detail, severity, post_id, object_type, object_id, first_seen_run FROM {$table} WHERE run_id = %d ORDER BY type, id",
				$run_id
			),
			ARRAY_A
		);
		// phpcs:enable WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.NoCaching,WordPress.DB.PreparedSQL.InterpolatedNotPrepared

		$grouped = array();
		foreach ( $rows as $row ) {
			$detail                    = json_decode( (string) $row['detail'], true );
			$row['detail']             = is_array( $detail ) ? $detail : array();
			$row['object_type']        = (string) ( $row['object_type'] ?? '' );
			$row['object_id']          = (int) ( $row['object_id'] ?? 0 );
			$row['is_new']             = (int) $row['first_seen_run'] === $run_id;
			$grouped[ $row['type'] ][] = $row;
		}

		return $grouped;
	}

	/**
	 * Stamp an issue row's detail JSON with fixed_at so the dashboard can
	 * render it as resolved-pending-recrawl. The row itself is kept — the
	 * next crawl is the source of truth.
	 *
	 * @param int $issue_id Issue row ID.
	 */
	public static function mark_fixed( int $issue_id ): void {
		global $wpdb;

		$table = $wpdb->prefix . self::TABLE_ISSUES;

		// phpcs:disable WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.NoCaching,WordPress.DB.PreparedSQL.InterpolatedNotPrepared
		$raw = $wpdb->get_var( $wpdb->prepare( "SELECT detail FROM {$table} WHERE id = %d", $issue_id ) );
		if ( null === $raw ) {
			return;
		}

		$detail             = is_array( json_decode( (string) $raw, true ) ) ? json_decode( (string) $raw, true ) : array();
		$detail['fixed_at'] = time();

		$wpdb->update(
			$table,
			array( 'detail' => wp_json_encode( $detail ) ),
			array( 'id' => $issue_id ),
			array( '%s' ),
			array( '%d' )
		);
		// phpcs:enable WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.NoCaching,WordPress.DB.PreparedSQL.InterpolatedNotPrepared
	}

	/**
	 * Return the most recent distinct run IDs, newest first.
	 *
	 * Used by the Site Audit dashboard to locate the previous run (for triage
	 * deltas) and to build the trend strip.
	 *
	 * @param int $limit Maximum number of run IDs to return. Default 5.
	 * @return int[] Run IDs, newest first.
	 */
	public static function latest_run_ids( int $limit = 5 ): array {
		global $wpdb;

		$table = $wpdb->prefix . self::TABLE_QUEUE;

		// phpcs:disable WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.NoCaching,WordPress.DB.PreparedSQL.InterpolatedNotPrepared
		$ids = $wpdb->get_col(
			$wpdb->prepare(
				"SELECT DISTINCT run_id FROM {$table} ORDER BY run_id DESC LIMIT %d",
				$limit
			)
		);
		// phpcs:enable WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.NoCaching,WordPress.DB.PreparedSQL.InterpolatedNotPrepared

		return array_map( 'intval', $ids );
	}

	/**
	 * Return the crawled-URL count for the given run.
	 *
	 * @param int $run_id Target run ID.
	 * @return int
	 */
	public static function crawled_count( int $run_id ): int {
		global $wpdb;

		$table = $wpdb->prefix . self::TABLE_QUEUE;

		// phpcs:disable WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.NoCaching,WordPress.DB.PreparedSQL.InterpolatedNotPrepared
		return (int) $wpdb->get_var(
			$wpdb->prepare(
				"SELECT COUNT(*) FROM {$table} WHERE run_id = %d AND status = 'done'",
				$run_id
			)
		);
		// phpcs:enable WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.NoCaching,WordPress.DB.PreparedSQL.InterpolatedNotPrepared
	}

	// =========================================================================
	// PRUNING
	// =========================================================================

	/**
	 * Remove queue + issue rows for runs older than the retention window.
	 *
	 * Keeps the RUNS_TO_KEEP most-recent completed runs.
	 *
	 * @param int $current_run_id The run just completed.
	 */
	public static function prune_old_runs( int $current_run_id ): void {
		global $wpdb;

		$queue_table  = $wpdb->prefix . self::TABLE_QUEUE;
		$issues_table = $wpdb->prefix . self::TABLE_ISSUES;
		$pages_table  = $wpdb->prefix . self::TABLE_PAGES;

		// phpcs:disable WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.NoCaching,WordPress.DB.PreparedSQL.InterpolatedNotPrepared
		$old_runs = $wpdb->get_col(
			$wpdb->prepare(
				"SELECT DISTINCT run_id FROM {$queue_table} WHERE run_id < %d ORDER BY run_id DESC LIMIT 999 OFFSET %d",
				$current_run_id,
				self::RUNS_TO_KEEP - 1
			)
		);
		// phpcs:enable WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.NoCaching,WordPress.DB.PreparedSQL.InterpolatedNotPrepared

		if ( empty( $old_runs ) ) {
			return;
		}

		$placeholders = implode( ',', array_fill( 0, count( $old_runs ), '%d' ) );

		// phpcs:disable WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.NoCaching,WordPress.DB.PreparedSQL.InterpolatedNotPrepared,WordPress.DB.PreparedSQLPlaceholders.UnfinishedPrepare
		$wpdb->query( $wpdb->prepare( "DELETE FROM {$queue_table} WHERE run_id IN ({$placeholders})", ...$old_runs ) );
		$wpdb->query( $wpdb->prepare( "DELETE FROM {$issues_table} WHERE run_id IN ({$placeholders})", ...$old_runs ) );
		$wpdb->query( $wpdb->prepare( "DELETE FROM {$pages_table} WHERE run_id IN ({$placeholders})", ...$old_runs ) );
		// phpcs:enable WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.NoCaching,WordPress.DB.PreparedSQL.InterpolatedNotPrepared,WordPress.DB.PreparedSQLPlaceholders.UnfinishedPrepare
	}
}
